# Generated by Django 4.1.3 on 2022-11-12 17:57

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "activity_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(max_length=1024, verbose_name="Activity Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "child_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="Full Name")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("want_pet", models.BooleanField(default=False)),
                ("about_me", models.TextField(verbose_name="About me")),
                (
                    "emergency_contact",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("activity_pref", models.ManyToManyField(to="topy.activity")),
            ],
        ),
        migrations.CreateModel(
            name="TOPYStation",
            fields=[
                (
                    "station_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "station_name",
                    models.CharField(max_length=1024, verbose_name="Full Name"),
                ),
                (
                    "address1",
                    models.CharField(max_length=1024, verbose_name="Address line 1"),
                ),
                (
                    "address2",
                    models.CharField(max_length=1024, verbose_name="Address line 2"),
                ),
                (
                    "zip_code",
                    models.CharField(max_length=12, verbose_name="ZIP / Postal code"),
                ),
                ("city", models.CharField(max_length=1024, verbose_name="City")),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("password", models.CharField(max_length=40, verbose_name="Password")),
                ("name", models.CharField(max_length=1024, verbose_name="Full Name")),
                (
                    "address1",
                    models.CharField(max_length=1024, verbose_name="Address line 1"),
                ),
                (
                    "address2",
                    models.CharField(max_length=1024, verbose_name="Address line 2"),
                ),
                (
                    "zip_code",
                    models.CharField(max_length=12, verbose_name="ZIP / Postal code"),
                ),
                ("city", models.CharField(max_length=1024, verbose_name="City")),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserType",
            fields=[
                (
                    "user_type_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(max_length=1024, verbose_name="User Type Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeniorCitizen",
            fields=[
                (
                    "senior_citizen_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="Full Name")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("want_pet", models.BooleanField(default=True)),
                ("want_child", models.BooleanField(default=True)),
                ("about_me", models.TextField(verbose_name="About me")),
                (
                    "emergency_contact",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("activity_pref", models.ManyToManyField(to="topy.activity")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="topy.user"
                    ),
                ),
                (
                    "user_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="topy.usertype"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "pet_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="Full Name")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "pet_animal_type",
                    models.CharField(max_length=1024, verbose_name="Animal Species"),
                ),
                (
                    "pet_breed",
                    models.CharField(max_length=1024, verbose_name="Pet Breed"),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("about_me", models.TextField(verbose_name="About me")),
                (
                    "emergency_contact",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("activity_pref", models.ManyToManyField(to="topy.activity")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="topy.user"
                    ),
                ),
                (
                    "user_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="topy.usertype"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "match_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("status", models.CharField(max_length=1024, verbose_name="Status")),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="topy.child"
                    ),
                ),
                (
                    "initiator_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="topy.usertype"
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="topy.pet"
                    ),
                ),
                (
                    "senior_citizen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="topy.seniorcitizen",
                    ),
                ),
                (
                    "topy_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="topy.topystation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="child",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="topy.user"
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="user_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="topy.usertype"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="user_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="topy.usertype"
            ),
        ),
    ]
