# Generated by Django 4.1.3 on 2022-11-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="child",
            name="child_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="match",
            name="match_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="pet",
            name="pet_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="seniorcitizen",
            name="senior_citizen_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="topystation",
            name="station_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="usertype",
            name="user_type_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
