# Generated by Django 4.1.3 on 2022-11-28 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("topy", "0003_remove_seniorcitizen_birthday_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="activity", name="user_type",),
        migrations.RemoveField(model_name="child", name="user_type",),
        migrations.RemoveField(model_name="pet", name="user_type",),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="topy.usertype",
            ),
            preserve_default=False,
        ),
    ]
