# Generated by Django 4.1.3 on 2022-12-04 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("topy", "0004_remove_activity_user_type_remove_child_user_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="user_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="topy.usertype",
            ),
            preserve_default=False,
        ),
    ]
