# Generated by Django 3.2.16 on 2022-12-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topy', '0008_auto_20221205_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
