# Generated by Django 3.2.16 on 2022-12-07 00:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('topy', '0009_remove_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniorcitizen',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seniorcitizen',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='seniorcitizen',
            name='name',
            field=models.CharField(default=1, max_length=1024, verbose_name='Full Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seniorcitizen',
            name='about_me',
            field=models.TextField(blank=True, verbose_name='About me'),
        ),
        migrations.AlterField(
            model_name='seniorcitizen',
            name='activity_pref',
            field=models.ManyToManyField(blank=True, to='topy.Activity'),
        ),
        migrations.AlterField(
            model_name='seniorcitizen',
            name='emergency_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
