# Generated by Django 3.2.16 on 2022-12-07 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topy', '0010_auto_20221206_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topy.pet'),
        ),
    ]
