# Generated by Django 4.1.3 on 2022-11-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trialtwo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trialuser",
            name="name",
            field=models.CharField(max_length=1024, verbose_name="Full Name"),
        ),
    ]
