# Generated by Django 4.1.3 on 2022-11-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Try",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=1024, verbose_name="Full Name")),
            ],
        ),
    ]
