# Generated by Django 4.1.3 on 2022-11-11 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("try", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Try", new_name="Try_user",),
    ]
